### ISSUE TITLE
memql: wrong type argument listp count

### ISSUE THREAD

**Issue by lonelymtn** [iqbalansari/mu4e-alert#14] opened 2016-05-23 20:07 UTC
Started getting this error, after each database update, a couple of days ago.  Running emacs 24.5, mu4e-alert 20160215.209 from melpa, mu 0.9.17 C from github

> Debugger entered--Lisp error: (wrong-type-argument listp count)
>   memql(count count)
>   #[257 "\301!\302\30\"\203\304G!\210\302\30\"\205\306!\207" [mu4e-alert-email-notification-types mu4e-alert-filter-repeated-mails memql count mu4e-alert-notify-unread-messages-count subjects mu4e-alert-notify-unread-messages] 5 "\n\n(fn MAILS)"](nil)
>   #[514 "\301\302!\303\"\205\300\304\305!!!\207" [#[257 "\301!\302\30\"\203\304G!\210\302\30\"\205\306!\207" [mu4e-alert-email-notification-types mu4e-alert-filter-repeated-mails memql count mu4e-alert-notify-unread-messages-count subjects mu4e-alert-notify-unread-messages] 5 "\n\n(fn MAILS)"] memql process-status (exit signal) mu4e-alert--parse-mails process-buffer] 6 "\n\n(fn PROCESS ##)"](#<process mu4e-unread-mails)

**Comment by iqbalansari** [comment] 2016-05-30 06:23
Hi,

I am not able to reproduce this similar configuration that you have mentioned. I think that somehow the value of the variable `mu4e-alert-email-notification-types` is set to just `'count`, while it should ideally be a list (see the [Readme](https://github.com/iqbalansari/mu4e-alert#customizing-the-types-of-notifications-displayed)) in your configuration, could you please post the value of the variable?

Thanks

**Comment by lonelymtn** [comment] 2016-05-31 17:06
It is set to just count, as that is the only type that I wish to receive.  Here is my config:

```
(setq mu4e-alert-style 'notifications
  mu4e-alert-email-notification-types 'count)
(add-hook 'after-init-hook #'mu4e-alert-enable-notifications)
(add-hook 'after-init-hook #'mu4e-alert-enable-mode-line-display)
```

Suggestions on a value to set mu4e-alert-email-notification-types to in order to just receive counts?

thanks.

**Comment by lonelymtn** [comment] 2016-05-31 20:37
@iqbalansari 

Changing my value to:

`(setq mu4e-alert-email-notification-types '(count))`

Fixed the issue.  Thank you.

**Comment by iqbalansari** [comment] 2016-06-01 05:14
Glad you got it working, I am closing this issue. Any suggestions on improving the documentation?

Thanks

**Closed as completed** 2016-06-01 05:14 UTC
Labels: invalid

**Comment by lonelymtn** [comment] 2016-06-02 21:03
I would recommend a concrete example of setting the value of the variable, that can go a long way.  A single line is all that is needed.

thanks.
