### ISSUE TITLE
clear fringe alert?

### ISSUE THREAD

**Issue by zeltak** [iqbalansari/mu4e-alert#4] opened 2015-11-06 11:40 UTC
Hi!

first of all a huge thx for mu4e-alert, its fantastic!

I have a question about the fringe alert. i enabled it using your example and it does work. the problem is that is colors all my scattered emacs client windows and also i can seem to see how to clear it? i dont have any more unread messages but the fringe is still present

best

Z

**Comment by iqbalansari** [comment] 2015-11-06 15:34
Hi!

It seems you have a hit a bug in [alert](https://github.com/jwiegley/alert/) package (`mu4e-alert` uses it for notifications). By default it removes fringe alert after any command by the user, it seems to be working for me. Can you add the version of alert package on your system? Also what is the Emacs version you are using?

**Comment by zeltak** [comment] 2015-11-06 15:59
Hi

sure , im using GNU Emacs 24.5.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.16.6)
and alert  version  20151018.912

best

Z

**Comment by iqbalansari** [comment] 2015-11-06 16:08
Strange, I am on similar configuration but have no issues. Could restart emacs and try again? In case that fails, the code to restore the fringe is [here](https://github.com/jwiegley/alert/blob/a9c267b4f82b10a1aa194153fb5a53d0b26d2718/alert.el#L587-L588), just try manually evaluating `(copy-face 'alert-saved-fringe-face 'fringe)`, perhaps that might give some clues. 

Also try doing <kbd>M-x</kbd>`describe-face`<kbd>RET</kbd>`alert-saved-fringe-face`<kbd>RET</kbd>, this should have the background and foreground set to the original background and foreground colors of the fringe.

**Comment by iqbalansari** [comment] 2015-11-11 13:46
Hi @zeltak , did you manage to resolve the issue?

**Comment by zeltak** [comment] 2015-11-11 14:53
Hi again

restarting emacs dosent seem to help the issue and i still get the persistent fringe color. using the `copy-face 'alert-saved-fringe-face 'fringe)` command does indeed work manually to clear the fringe.
im a neewb in emacs and generally suck at coding but would be very happy to help out debugging (if given instructions :))!

best

Z

**Comment by gaydenko** [comment] 2016-02-09 12:11
I'm the next affected by the issue. Emacs from (yesterday at the moment) git is in use. Arch Linux, KDE. All packages in use are up to date in accordance with current MELPA state.

Must I supply any additional info?

I haven't found that operation to avoid the frame taking attention (that is being pink in Task Manage panel).

**Comment by iqbalansari** [comment] 2016-02-10 17:06
Hi @gaydenko,

Unfortunately I am unable to reproduce this on my Emacs. As I said earlier this most likely is a bug in the [alert](https://github.com/jwiegley/alert/) library. 

In case you are familiar with elisp debugging, could try to edebug the function `alert-fringe-restore` in `alert.el` and check if it is being called after you execute any command once the fringe is highlighted?

**Comment by gaydenko** [comment] 2016-02-10 18:04
@iqbalansari , I'm new with elisp, so edebugging will take some time to learn. I'll report as soon as get some results.

**Comment by gaydenko** [comment] 2016-02-10 22:25
@iqbalansari , I have both tried to instrument that function and to monkey patch with

``` lisp
(require `alert)
(defun alert-fringe-restore (info)
  (copy-face 'alert-saved-fringe-face 'fringe)
  (message "fringe restoring"))
```

But was unable to reach stop point or to get the message.

**Comment by iqbalansari** [comment] 2016-02-11 03:44
Hmm.. can you check the value of `post-command-hook` (just do <kbd>C-h</kbd><kbd>v</kbd> `post-command-hook` <kbd>RET</kbd>). Ideally it should be a list and should have `alert-remove-on-command` as one of the elements.

**Comment by gaydenko** [comment] 2016-02-11 08:17
@iqbalansari , yes, of course, it's here:

``` txt
post-command-hook is a variable defined in ‘C source code’.
Its value is (company-post-command t)
Local in buffer *mu4e-view*; global value is 
(global-font-lock-mode-check-buffers global-undo-tree-mode-check-buffers projectile-global-mode-check-buffers global-company-mode-check-buffers smartparens-global-mode-check-buffers magit-auto-revert-mode-check-buffers global-flycheck-mode-check-buffers sp--post-command-hook-handler sml/generate-position-help eldoc-schedule-timer)
```

So, there isn't any alert-related handlers in the list.

**Comment by iqbalansari** [comment] 2016-02-11 09:14
That hook is setup by `alert-send-notification` defined in `alert.el` could you please try instrumenting that function and see if it is setting up the hook?

**Comment by gaydenko** [comment] 2016-02-11 09:43
Yes, it does. I have noticed the hook is adding against `alert-buffer` argument. Does it mean operations are counted on that buffer only? And what is that buffer is? :) I have look at that var and got `alert-buffer’s value is #<buffer  *mu4e-mails*-473611>`. What if this buffer is then just closed/killed? Is it an operation? 

At the moment I have tried to set `message-kill-buffer-on-exit` to `nil` (while all other time it was `t`), but still got the issue.

**Comment by iqbalansari** [comment] 2016-02-11 10:40
Right, that might be a problem, the hook is added by alert only of for the currently selected buffer. I have pushed a fix to master which does not change the buffer while retrieving the mails. Could you please try it out once MELPA builds the new version and report back if it worked?

**Comment by gaydenko** [comment] 2016-02-11 11:05
Unfortunately with 6f8df55b the issue still exists.

**Comment by iqbalansari** [comment] 2016-02-11 16:15
What is the value `post-command-hook` after the changes introduced in 6f8df55b. Does it have element `alert-remove-on-command`?

**Comment by gaydenko** [comment] 2016-02-11 16:36
I haven't got the var in the list. 

But I have noticed sometimes frame decoration returns to normal mode from alert mode. Just didn't understand yet the flows which result in keeping alert mode and returning to normal mode. That is "sometimes it works".

I guess it is needed more time to grok current behavior.

**Comment by iqbalansari** [comment] 2016-02-11 17:56
The unfortunate part is I have not been able to reproduce this, I have tried on atleast two machines and the fringe restore part seems to work well. Just to be sure when you say fringe color is not restored you mean 
- The fringe color does not go back to the color it  before the alert?
- The fringe color turns green and then after a command turns to some other color (which is neither green nor the initial color of the fringe)

I have recently observed the second behavior and I guess I know the reason for it.

As for the flow, the decoration is added by `alert-send-notification` which [sends](https://github.com/jwiegley/alert/blob/dfb003476aeb26d08782c17257f3a81934bcf6ce/alert.el#L878-L880) a notification using the function `:notifier` property of an alert style, it also records the current alert in `alert-active-alerts` (along with some information about the alert and the function to remove the alert) and [adds](https://github.com/jwiegley/alert/blob/dfb003476aeb26d08782c17257f3a81934bcf6ce/alert.el#L883-L884) `alert-remove-on-command` to `post-command-hook` if the current alert style has `:remover` property. `post-command-hook` is basically a set of functions that are called by Emacs whenever a command is executed. 

This `alert-remove-on-command` will be executed whenever you execute the next command that function simply goes through active alerts removes them if they specify a remover function (the function is `alert-fringe-restore` in case of fringe alerts)

So I guess the functions to check are 
- `alert-send-notification`, is it adding the `post-command-hook` and recording the fringe alert correctly? Based on inputs so far I am pretty sure there is some bug in this function that is causing the issue.
-  `alert-remove-on-command`, is it looping through the active alerts and removing them correctly? I think this is unlikely
- `alert-fringe-restore`, is actually restoring the fringe? This can be a potential issue.

Thanks for you efforts. Let me see if I can get arch running on vagrant and try to reproduce the issue.

**Comment by gaydenko** [comment] 2016-02-11 18:19
Iqbal Ansari notifications@github.com writes:

>    The unfortunate part is I have not been able to reproduce this, I have
>    tried on atleast two machines and the fringe restore part seems to work
>    well. Just to be sure when you say fringe color is not restored you
>    mean
>      \* The fringe color does not go back to the color it before the alert?
>      \* The fringe color turns green and then after a command turns to some
>        other color (which is neither green nor the initial color of the
>        fringe)

Under Linux/KDE/selected-color-theme not-focused "window needs
attention" (alert) is decorated as pink bg for not-focused task on the
taskbar (while focused window regardless alert is shown with blue bg,
and not-focused not-alerted one - with gray bg).

So I mean the first - switching to alert Emacs frame, doing some
operation (say, opening new message) and switching to another process
results in reappearing of ping (alert) decoration of the Emacs frame.

>    I have recently observed the second behavior and I guess I know the
>    reason for it.
> 
>    As for the flow, the decoration is added by alert-send-notification
>    which [1]sends a notification using the function :notifier property of
>    an alert style, it also records the current alert in
>    alert-active-alerts (along with some information about the alert and
>    the function to remove the alert) and [2]adds alert-remove-on-command
>    to post-command-hook if the current alert style has :remover property.
>    post-command-hook is basically a set of functions that are called by
>    Emacs whenever a command is executed.
> 
>    This alert-remove-on-command will be executed whenever you execute the
>    next command that

What is "command" at the context? Is opening a message, or jumping to
context or folder. or quiting headers view, or opening some buffer a "command"?

> function simply goes through active alerts removes
>    them if they specify a remover function (the function is
>    alert-fringe-restore in case of fringe alerts)
> 
>    So I guess the functions to check are
>      \* alert-send-notification, is it adding the post-command-hook and
>        recording the fringe alert correctly? Based on inputs so far I am
>        pretty sure there is some bug in this function that is causing the
>        issue.
>      \* alert-remove-on-command, is it looping through the active alerts
>        and removing them correctly? I think this is unlikely
>      \* alert-fringe-restore, is actually restoring the fringe? This can be
>        a potential issue.
> 
>    Thanks for you efforts. Let me see if I can get arch running on vagrant
>    and try to reproduce the issue.

I of course also will supply any information would it be not too
vague. Alerting is very handy feature, thanks for the extension!

P.S. I'm just invetsigating both mu4e and, by demands, learning elisp a little,
and it is the first not-for-testing message from mu4e :)

## 

Regards,
Andrew

**Comment by gaydenko** [comment] 2016-02-14 10:03
Probably I must emphasize at my case the issue takes place with "window needs attention" decoration which means a window-related panel on the task bar is decorated (not the frame itself). Fringe decoration of Emacs frame (green edges at my case) disappears as expected. 

Probably it is just another issue rather issue creator has got. On the attached picture you can see 'mail-frame' has pink bg as a result of alerting, while I even already have read new message.

![mu-alert01](https://cloud.githubusercontent.com/assets/3740016/13033089/f195f30a-d31a-11e5-8547-d8b4348b3814.png)

**Comment by iqbalansari** [comment] 2016-02-14 12:25
Yes your issue, seems to be unrelated to the one reported by @zeltak. `mu4e-alert` sets window urgency. I was under the impression that window managers clear the urgency hint after you select the window, I think I was wrong, I will try to push a fix for this soon. Meanwhile could you try setting `mu4e-alert-set-window-urgency` to `nil`.

@zeltak Can you still reproduce this issue?

**Comment by iqbalansari** [comment] 2016-02-14 12:28
@gaydenko When do you think is a good time to clear the urgency hint, is it okay to clear it once Emacs gets focus, irrespective of whether there are unread email?

**Comment by gaydenko** [comment] 2016-02-14 12:32
I guess it would.

Iqbal Ansari notifications@github.com writes:

> @gaydenko When do you think is a good time to clear the urgency hint, is it okay to clear it once Emacs gets focus, irrespective of whether there are unread email?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/iqbalansari/mu4e-alert/issues/4#issuecomment-183881843

## 

Regards,
Andrew

**Comment by gaydenko** [comment] 2016-02-14 12:42
Yes, with this var set to nil I don't get "window attention" at all.

Iqbal Ansari notifications@github.com writes:

> Yes your issue, seems to be unrelated to the one reported by @zeltak. `mu4e-alert` sets window urgency. I was under the impression that window managers clear the urgency hint after you select the window, I think I was wrong, I will try to push a fix for this soon. Meanwhile could you try setting `mu4e-alert-set-window-urgency` to `nil`.

## 

Regards,
Andrew

**Comment by iqbalansari** [comment] 2016-02-14 13:30
@gaydenko I have pushed a fix on master to clear the window urgency hint after selecting Emacs. Please do test and let me know if it works (you need not set `mu4e-alert-set-window-urgency` to `nil` now) .

**Comment by gaydenko** [comment] 2016-02-14 13:53
Yes, now urgency hint works as expected, thanks!

But it has got a side-effect :) On any frame focus or un-focus I get
system beep with the error in Messages buffer:

and: Window system frame should be used [6 times]

Iqbal Ansari notifications@github.com writes:

> @gaydenko I have pushed a fix on master to clear the window urgency hint after selecting Emacs. Please do test and let me know if it works (you need not set `mu4e-alert-set-window-urgency` to `nil` now) .
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/iqbalansari/mu4e-alert/issues/4#issuecomment-183889376

## 

Regards,
Andrew

**Comment by iqbalansari** [comment] 2016-02-14 14:03
Are you using Emacs inside a terminal?

Also do <kbd>M-x</kbd>`toggle-debug-on-error`<kbd>RET</kbd>, this would give a stacktrace when the error happens, could post the stacktrace?

**Comment by gaydenko** [comment] 2016-02-14 14:59
Iqbal Ansari notifications@github.com writes:

> Are you using Emacs inside a terminal?

Mostly as window frame, but sometimes - rather rare - in terminal.
All current reports are related with frames only.

> Also do <kbd>M-x</kbd>`toggle-debug-on-error`<kbd>RET</kbd>, this
> would give a stacktrace when the error happens, could post the
> stacktrace?

For some reason I haven't got all commits at that moment. Then I have pulled from
repository again, and the error (beep) has gone. But window urgent hint
also stopped to appear on new message arriving.
To be precise, c18d22f7 is in use at the moment.

## 

Regards,
Andrew

**Comment by gaydenko** [comment] 2016-02-14 15:30
Probably I must to add, frames as used in a form of Emacs client - Emacs daemon is in use.

**Comment by iqbalansari** [comment] 2016-02-14 16:21
I have pushed fix for the error you mentioned earlier. As for window urgency hint being not set, `mu4e-alert` does not set it if the Emacs frame is visible, I thought it is redundant. What are your thoughts on this?

**Comment by gaydenko** [comment] 2016-02-14 16:31
Iqbal Ansari notifications@github.com writes:

> I have pushed fix for the error you mentioned earlier. As for window urgency hint being not set, `mu4e-alert` does not set it if the Emacs frame is visible, I thought it is redundant. What are your thoughts on this?

I'm not sure what is the strict meaning of "visible". Is a window
visible when it is on some another virtual desktop? behind other window?
I guess "fire the window if it is not focused" would work more expected way.

## 

Regards,
Andrew

**Comment by iqbalansari** [comment] 2016-02-14 16:38
I guess I will go with much simpler option of always setting urgency hint, you mentioned some valid edge cases which I think would be difficult to handle.

**Comment by gaydenko** [comment] 2016-02-14 16:41
Iqbal Ansari notifications@github.com writes:

> I have pushed fix for the error you mentioned earlier. As for window urgency hint being not set, `mu4e-alert` does not set it if the Emacs frame is visible, I thought it is redundant. What are your thoughts on this?

Also I have noticed: say, I have got two new emails, appropriate
notifications were sent. Then I open the first message, prepare reply
and send it. Then I get repeated notifications regarding the remaining new
message (the second one among already received) I did not read yet. 

## 

Regards
975

**Comment by iqbalansari** [comment] 2016-02-14 16:46
Yes this is a known issue, see #12, I will push a fix for this soon. 

I am assuming the issues you mentioned previously have been fixed. Thanks for patience and inputs

**Comment by gaydenko** [comment] 2016-02-14 16:47
Iqbal Ansari notifications@github.com writes:

> I guess I will go with much simpler option of always setting urgency hint, you mention some valid edge cases which I think would be difficult to handle.

To tell the truth, these "edge" use cases take 100% of my normal work
flow :) I even can not imagine another ones except for multi-monitor
configurations, but it isn't too common.

I would look at the urgency hint just as handy way to notice "new
messages arrived" event even being not close to the screen. Some kind of
convenient indicator.

Other ways are not such handy:
- system tray icon is too small to be noticeable form few meters
  distance
- desktop indicators demands windows be not-maximized

But urgency hint has not all these drawbacks.

## 

Regards,
Andrew

**Comment by iqbalansari** [comment] 2016-02-14 16:54
> To tell the truth, these "edge" use cases take 100% of my normal work flow :) I even can not imagine another ones except for multi-monitor configurations, but it isn't too common

True, but I do not think it is possible to detect if an Emacs frame has focus (and is not just visible) without using an external tool. In the current case the only disadvantage is that the urgency hint is set even if Emacs is currently focused, which I think is a minor annoyance.

**Comment by gaydenko** [comment] 2016-02-15 23:55
@iqbalansari , hi! During this period I just used mu4e ordinary way, and I guess current git state of mu-alert is optimal at my case. Thanks for the fixing!

**Comment by iqbalansari** [comment] 2016-02-16 05:05
@gaydenko Glad I could help you :smile:

**Comment by iqbalansari** [comment] 2016-03-02 08:59
@zeltak Closing this for now, feel free to open if you manage to come up with  a reproducible recipe. Thanks

**Closed as completed** 2016-03-02 08:58 UTC
Labels: question
